#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanAoDoAn.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATA-SHOP-QUAN-AO")]
	public partial class DbWebQuanAoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMAU(MAU instance);
    partial void UpdateMAU(MAU instance);
    partial void DeleteMAU(MAU instance);
    partial void InsertLOAI_SP(LOAI_SP instance);
    partial void UpdateLOAI_SP(LOAI_SP instance);
    partial void DeleteLOAI_SP(LOAI_SP instance);
    partial void InsertDON_DAT_HANG(DON_DAT_HANG instance);
    partial void UpdateDON_DAT_HANG(DON_DAT_HANG instance);
    partial void DeleteDON_DAT_HANG(DON_DAT_HANG instance);
    partial void InsertCT_DON_HANG(CT_DON_HANG instance);
    partial void UpdateCT_DON_HANG(CT_DON_HANG instance);
    partial void DeleteCT_DON_HANG(CT_DON_HANG instance);
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertHINH_ANH(HINH_ANH instance);
    partial void UpdateHINH_ANH(HINH_ANH instance);
    partial void DeleteHINH_ANH(HINH_ANH instance);
    partial void InsertKICH_THUOC(KICH_THUOC instance);
    partial void UpdateKICH_THUOC(KICH_THUOC instance);
    partial void DeleteKICH_THUOC(KICH_THUOC instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertSAN_PHAM(SAN_PHAM instance);
    partial void UpdateSAN_PHAM(SAN_PHAM instance);
    partial void DeleteSAN_PHAM(SAN_PHAM instance);
    #endregion
		
		public DbWebQuanAoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATA_SHOP_QUAN_AOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbWebQuanAoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAU> MAUs
		{
			get
			{
				return this.GetTable<MAU>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_SP> LOAI_SPs
		{
			get
			{
				return this.GetTable<LOAI_SP>();
			}
		}
		
		public System.Data.Linq.Table<DON_DAT_HANG> DON_DAT_HANGs
		{
			get
			{
				return this.GetTable<DON_DAT_HANG>();
			}
		}
		
		public System.Data.Linq.Table<CT_DON_HANG> CT_DON_HANGs
		{
			get
			{
				return this.GetTable<CT_DON_HANG>();
			}
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this.GetTable<HINH_ANH>();
			}
		}
		
		public System.Data.Linq.Table<KICH_THUOC> KICH_THUOCs
		{
			get
			{
				return this.GetTable<KICH_THUOC>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this.GetTable<SAN_PHAM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAU")]
	public partial class MAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_MAU;
		
		private string _TEN_MAU;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_MAUChanging(string value);
    partial void OnMA_MAUChanged();
    partial void OnTEN_MAUChanging(string value);
    partial void OnTEN_MAUChanged();
    #endregion
		
		public MAU()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MAU", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_MAU
		{
			get
			{
				return this._MA_MAU;
			}
			set
			{
				if ((this._MA_MAU != value))
				{
					this.OnMA_MAUChanging(value);
					this.SendPropertyChanging();
					this._MA_MAU = value;
					this.SendPropertyChanged("MA_MAU");
					this.OnMA_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MAU", DbType="NVarChar(20)")]
		public string TEN_MAU
		{
			get
			{
				return this._TEN_MAU;
			}
			set
			{
				if ((this._TEN_MAU != value))
				{
					this.OnTEN_MAUChanging(value);
					this.SendPropertyChanging();
					this._TEN_MAU = value;
					this.SendPropertyChanged("TEN_MAU");
					this.OnTEN_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="MA_MAU", OtherKey="MA_MAU")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.MAU = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.MAU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_SP")]
	public partial class LOAI_SP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_LOAI;
		
		private string _TEN_LOAI;
		
		private EntitySet<SAN_PHAM> _SAN_PHAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LOAIChanging(int value);
    partial void OnMA_LOAIChanged();
    partial void OnTEN_LOAIChanging(string value);
    partial void OnTEN_LOAIChanged();
    #endregion
		
		public LOAI_SP()
		{
			this._SAN_PHAMs = new EntitySet<SAN_PHAM>(new Action<SAN_PHAM>(this.attach_SAN_PHAMs), new Action<SAN_PHAM>(this.detach_SAN_PHAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI", DbType="NVarChar(20)")]
		public string TEN_LOAI
		{
			get
			{
				return this._TEN_LOAI;
			}
			set
			{
				if ((this._TEN_LOAI != value))
				{
					this.OnTEN_LOAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI = value;
					this.SendPropertyChanged("TEN_LOAI");
					this.OnTEN_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SP_SAN_PHAM", Storage="_SAN_PHAMs", ThisKey="MA_LOAI", OtherKey="MA_LOAI")]
		public EntitySet<SAN_PHAM> SAN_PHAMs
		{
			get
			{
				return this._SAN_PHAMs;
			}
			set
			{
				this._SAN_PHAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SP = this;
		}
		
		private void detach_SAN_PHAMs(SAN_PHAM entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_SP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON_DAT_HANG")]
	public partial class DON_DAT_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DON_HANG;
		
		private System.Nullable<int> _MA_KH;
		
		private System.DateTime _NGAY_DAT;
		
		private System.Nullable<System.DateTime> _NGAY_GIAO;
		
		private System.Nullable<bool> _DA_THANH_TOAN;
		
		private System.Nullable<bool> _TINH_TRANG_GH;
		
		private EntitySet<CT_DON_HANG> _CT_DON_HANGs;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DON_HANGChanging(int value);
    partial void OnMA_DON_HANGChanged();
    partial void OnMA_KHChanging(System.Nullable<int> value);
    partial void OnMA_KHChanged();
    partial void OnNGAY_DATChanging(System.DateTime value);
    partial void OnNGAY_DATChanged();
    partial void OnNGAY_GIAOChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_GIAOChanged();
    partial void OnDA_THANH_TOANChanging(System.Nullable<bool> value);
    partial void OnDA_THANH_TOANChanged();
    partial void OnTINH_TRANG_GHChanging(System.Nullable<bool> value);
    partial void OnTINH_TRANG_GHChanged();
    #endregion
		
		public DON_DAT_HANG()
		{
			this._CT_DON_HANGs = new EntitySet<CT_DON_HANG>(new Action<CT_DON_HANG>(this.attach_CT_DON_HANGs), new Action<CT_DON_HANG>(this.detach_CT_DON_HANGs));
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DON_HANG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_DON_HANG
		{
			get
			{
				return this._MA_DON_HANG;
			}
			set
			{
				if ((this._MA_DON_HANG != value))
				{
					this.OnMA_DON_HANGChanging(value);
					this.SendPropertyChanging();
					this._MA_DON_HANG = value;
					this.SendPropertyChanged("MA_DON_HANG");
					this.OnMA_DON_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", DbType="Int")]
		public System.Nullable<int> MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_DAT
		{
			get
			{
				return this._NGAY_DAT;
			}
			set
			{
				if ((this._NGAY_DAT != value))
				{
					this.OnNGAY_DATChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT = value;
					this.SendPropertyChanged("NGAY_DAT");
					this.OnNGAY_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_GIAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_GIAO
		{
			get
			{
				return this._NGAY_GIAO;
			}
			set
			{
				if ((this._NGAY_GIAO != value))
				{
					this.OnNGAY_GIAOChanging(value);
					this.SendPropertyChanging();
					this._NGAY_GIAO = value;
					this.SendPropertyChanged("NGAY_GIAO");
					this.OnNGAY_GIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DA_THANH_TOAN", DbType="Bit")]
		public System.Nullable<bool> DA_THANH_TOAN
		{
			get
			{
				return this._DA_THANH_TOAN;
			}
			set
			{
				if ((this._DA_THANH_TOAN != value))
				{
					this.OnDA_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._DA_THANH_TOAN = value;
					this.SendPropertyChanged("DA_THANH_TOAN");
					this.OnDA_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINH_TRANG_GH", DbType="Bit")]
		public System.Nullable<bool> TINH_TRANG_GH
		{
			get
			{
				return this._TINH_TRANG_GH;
			}
			set
			{
				if ((this._TINH_TRANG_GH != value))
				{
					this.OnTINH_TRANG_GHChanging(value);
					this.SendPropertyChanging();
					this._TINH_TRANG_GH = value;
					this.SendPropertyChanged("TINH_TRANG_GH");
					this.OnTINH_TRANG_GHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_DAT_HANG_CT_DON_HANG", Storage="_CT_DON_HANGs", ThisKey="MA_DON_HANG", OtherKey="MA_DON_HANG")]
		public EntitySet<CT_DON_HANG> CT_DON_HANGs
		{
			get
			{
				return this._CT_DON_HANGs;
			}
			set
			{
				this._CT_DON_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DON_DAT_HANG", Storage="_KHACH_HANG", ThisKey="MA_KH", OtherKey="MA_KH", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.DON_DAT_HANGs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.DON_DAT_HANGs.Add(this);
						this._MA_KH = value.MA_KH;
					}
					else
					{
						this._MA_KH = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DON_HANGs(CT_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_DAT_HANG = this;
		}
		
		private void detach_CT_DON_HANGs(CT_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.DON_DAT_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_DON_HANG")]
	public partial class CT_DON_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DON_HANG;
		
		private int _MA_SP;
		
		private System.Nullable<int> _SL;
		
		private System.Nullable<decimal> _PHI_GIAO_HANG;
		
		private System.Nullable<decimal> _DON_GIA;
		
		private string _TEN_PHUONG_THUC_THANH_TOAN;
		
		private string _DIA_CHI;
		
		private System.Nullable<decimal> _TONG_TIEN;
		
		private EntityRef<DON_DAT_HANG> _DON_DAT_HANG;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DON_HANGChanging(int value);
    partial void OnMA_DON_HANGChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnPHI_GIAO_HANGChanging(System.Nullable<decimal> value);
    partial void OnPHI_GIAO_HANGChanged();
    partial void OnDON_GIAChanging(System.Nullable<decimal> value);
    partial void OnDON_GIAChanged();
    partial void OnTEN_PHUONG_THUC_THANH_TOANChanging(string value);
    partial void OnTEN_PHUONG_THUC_THANH_TOANChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnTONG_TIENChanging(System.Nullable<decimal> value);
    partial void OnTONG_TIENChanged();
    #endregion
		
		public CT_DON_HANG()
		{
			this._DON_DAT_HANG = default(EntityRef<DON_DAT_HANG>);
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DON_HANG", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_DON_HANG
		{
			get
			{
				return this._MA_DON_HANG;
			}
			set
			{
				if ((this._MA_DON_HANG != value))
				{
					if (this._DON_DAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DON_HANGChanging(value);
					this.SendPropertyChanging();
					this._MA_DON_HANG = value;
					this.SendPropertyChanged("MA_DON_HANG");
					this.OnMA_DON_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHI_GIAO_HANG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHI_GIAO_HANG
		{
			get
			{
				return this._PHI_GIAO_HANG;
			}
			set
			{
				if ((this._PHI_GIAO_HANG != value))
				{
					this.OnPHI_GIAO_HANGChanging(value);
					this.SendPropertyChanging();
					this._PHI_GIAO_HANG = value;
					this.SendPropertyChanged("PHI_GIAO_HANG");
					this.OnPHI_GIAO_HANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DON_GIA", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DON_GIA
		{
			get
			{
				return this._DON_GIA;
			}
			set
			{
				if ((this._DON_GIA != value))
				{
					this.OnDON_GIAChanging(value);
					this.SendPropertyChanging();
					this._DON_GIA = value;
					this.SendPropertyChanged("DON_GIA");
					this.OnDON_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PHUONG_THUC_THANH_TOAN", DbType="NVarChar(25)")]
		public string TEN_PHUONG_THUC_THANH_TOAN
		{
			get
			{
				return this._TEN_PHUONG_THUC_THANH_TOAN;
			}
			set
			{
				if ((this._TEN_PHUONG_THUC_THANH_TOAN != value))
				{
					this.OnTEN_PHUONG_THUC_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._TEN_PHUONG_THUC_THANH_TOAN = value;
					this.SendPropertyChanged("TEN_PHUONG_THUC_THANH_TOAN");
					this.OnTEN_PHUONG_THUC_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(50)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DON_DAT_HANG_CT_DON_HANG", Storage="_DON_DAT_HANG", ThisKey="MA_DON_HANG", OtherKey="MA_DON_HANG", IsForeignKey=true)]
		public DON_DAT_HANG DON_DAT_HANG
		{
			get
			{
				return this._DON_DAT_HANG.Entity;
			}
			set
			{
				DON_DAT_HANG previousValue = this._DON_DAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._DON_DAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DON_DAT_HANG.Entity = null;
						previousValue.CT_DON_HANGs.Remove(this);
					}
					this._DON_DAT_HANG.Entity = value;
					if ((value != null))
					{
						value.CT_DON_HANGs.Add(this);
						this._MA_DON_HANG = value.MA_DON_HANG;
					}
					else
					{
						this._MA_DON_HANG = default(int);
					}
					this.SendPropertyChanged("DON_DAT_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_CT_DON_HANG", Storage="_SAN_PHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.CT_DON_HANGs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.CT_DON_HANGs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TEN_DN_AD;
		
		private string _MK_DN_AD;
		
		private string _HINH_AD;
		
		private string _HO_TEN_AD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTEN_DN_ADChanging(string value);
    partial void OnTEN_DN_ADChanged();
    partial void OnMK_DN_ADChanging(string value);
    partial void OnMK_DN_ADChanged();
    partial void OnHINH_ADChanging(string value);
    partial void OnHINH_ADChanged();
    partial void OnHO_TEN_ADChanging(string value);
    partial void OnHO_TEN_ADChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DN_AD", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TEN_DN_AD
		{
			get
			{
				return this._TEN_DN_AD;
			}
			set
			{
				if ((this._TEN_DN_AD != value))
				{
					this.OnTEN_DN_ADChanging(value);
					this.SendPropertyChanging();
					this._TEN_DN_AD = value;
					this.SendPropertyChanged("TEN_DN_AD");
					this.OnTEN_DN_ADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK_DN_AD", DbType="NVarChar(50)")]
		public string MK_DN_AD
		{
			get
			{
				return this._MK_DN_AD;
			}
			set
			{
				if ((this._MK_DN_AD != value))
				{
					this.OnMK_DN_ADChanging(value);
					this.SendPropertyChanging();
					this._MK_DN_AD = value;
					this.SendPropertyChanged("MK_DN_AD");
					this.OnMK_DN_ADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_AD", DbType="NVarChar(MAX)")]
		public string HINH_AD
		{
			get
			{
				return this._HINH_AD;
			}
			set
			{
				if ((this._HINH_AD != value))
				{
					this.OnHINH_ADChanging(value);
					this.SendPropertyChanging();
					this._HINH_AD = value;
					this.SendPropertyChanged("HINH_AD");
					this.OnHINH_ADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO_TEN_AD", DbType="NVarChar(30)")]
		public string HO_TEN_AD
		{
			get
			{
				return this._HO_TEN_AD;
			}
			set
			{
				if ((this._HO_TEN_AD != value))
				{
					this.OnHO_TEN_ADChanging(value);
					this.SendPropertyChanging();
					this._HO_TEN_AD = value;
					this.SendPropertyChanged("HO_TEN_AD");
					this.OnHO_TEN_ADChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINH_ANH")]
	public partial class HINH_ANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HINH;
		
		private int _MA_SP;
		
		private string _HINH_ANH1;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HINHChanging(int value);
    partial void OnMA_HINHChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnHINH_ANH1Changing(string value);
    partial void OnHINH_ANH1Changed();
    #endregion
		
		public HINH_ANH()
		{
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_HINH
		{
			get
			{
				return this._MA_HINH;
			}
			set
			{
				if ((this._MA_HINH != value))
				{
					this.OnMA_HINHChanging(value);
					this.SendPropertyChanging();
					this._MA_HINH = value;
					this.SendPropertyChanged("MA_HINH");
					this.OnMA_HINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL")]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HINH_ANH", Storage="_HINH_ANH1", DbType="NVarChar(200)")]
		public string HINH_ANH1
		{
			get
			{
				return this._HINH_ANH1;
			}
			set
			{
				if ((this._HINH_ANH1 != value))
				{
					this.OnHINH_ANH1Changing(value);
					this.SendPropertyChanging();
					this._HINH_ANH1 = value;
					this.SendPropertyChanged("HINH_ANH1");
					this.OnHINH_ANH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_HINH_ANH", Storage="_SAN_PHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.HINH_ANHs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.HINH_ANHs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KICH_THUOC")]
	public partial class KICH_THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KICH_THUOC;
		
		private int _MA_SP;
		
		private string _TEN_KICH_THUOC;
		
		private EntityRef<SAN_PHAM> _SAN_PHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KICH_THUOCChanging(int value);
    partial void OnMA_KICH_THUOCChanged();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnTEN_KICH_THUOCChanging(string value);
    partial void OnTEN_KICH_THUOCChanged();
    #endregion
		
		public KICH_THUOC()
		{
			this._SAN_PHAM = default(EntityRef<SAN_PHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KICH_THUOC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KICH_THUOC
		{
			get
			{
				return this._MA_KICH_THUOC;
			}
			set
			{
				if ((this._MA_KICH_THUOC != value))
				{
					this.OnMA_KICH_THUOCChanging(value);
					this.SendPropertyChanging();
					this._MA_KICH_THUOC = value;
					this.SendPropertyChanged("MA_KICH_THUOC");
					this.OnMA_KICH_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", DbType="Int NOT NULL")]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					if (this._SAN_PHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KICH_THUOC", DbType="NVarChar(5)")]
		public string TEN_KICH_THUOC
		{
			get
			{
				return this._TEN_KICH_THUOC;
			}
			set
			{
				if ((this._TEN_KICH_THUOC != value))
				{
					this.OnTEN_KICH_THUOCChanging(value);
					this.SendPropertyChanging();
					this._TEN_KICH_THUOC = value;
					this.SendPropertyChanged("TEN_KICH_THUOC");
					this.OnTEN_KICH_THUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_KICH_THUOC", Storage="_SAN_PHAM", ThisKey="MA_SP", OtherKey="MA_SP", IsForeignKey=true)]
		public SAN_PHAM SAN_PHAM
		{
			get
			{
				return this._SAN_PHAM.Entity;
			}
			set
			{
				SAN_PHAM previousValue = this._SAN_PHAM.Entity;
				if (((previousValue != value) 
							|| (this._SAN_PHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SAN_PHAM.Entity = null;
						previousValue.KICH_THUOCs.Remove(this);
					}
					this._SAN_PHAM.Entity = value;
					if ((value != null))
					{
						value.KICH_THUOCs.Add(this);
						this._MA_SP = value.MA_SP;
					}
					else
					{
						this._MA_SP = default(int);
					}
					this.SendPropertyChanged("SAN_PHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KH;
		
		private string _TEN_KH;
		
		private string _SDT;
		
		private string _DIA_CHI;
		
		private string _TEN_DN;
		
		private string _MK_DN;
		
		private string _EMAIL;
		
		private System.Nullable<System.DateTime> _NGAY_SINH;
		
		private string _HINH_ANH;
		
		private System.Nullable<bool> _GIOI_TINH;
		
		private EntitySet<DON_DAT_HANG> _DON_DAT_HANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnTEN_KHChanging(string value);
    partial void OnTEN_KHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnTEN_DNChanging(string value);
    partial void OnTEN_DNChanged();
    partial void OnMK_DNChanging(string value);
    partial void OnMK_DNChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnNGAY_SINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_SINHChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnGIOI_TINHChanging(System.Nullable<bool> value);
    partial void OnGIOI_TINHChanged();
    #endregion
		
		public KHACH_HANG()
		{
			this._DON_DAT_HANGs = new EntitySet<DON_DAT_HANG>(new Action<DON_DAT_HANG>(this.attach_DON_DAT_HANGs), new Action<DON_DAT_HANG>(this.detach_DON_DAT_HANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KH", DbType="NVarChar(30)")]
		public string TEN_KH
		{
			get
			{
				return this._TEN_KH;
			}
			set
			{
				if ((this._TEN_KH != value))
				{
					this.OnTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._TEN_KH = value;
					this.SendPropertyChanged("TEN_KH");
					this.OnTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(50)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DN", DbType="NVarChar(50)")]
		public string TEN_DN
		{
			get
			{
				return this._TEN_DN;
			}
			set
			{
				if ((this._TEN_DN != value))
				{
					this.OnTEN_DNChanging(value);
					this.SendPropertyChanging();
					this._TEN_DN = value;
					this.SendPropertyChanged("TEN_DN");
					this.OnTEN_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MK_DN", DbType="NVarChar(50)")]
		public string MK_DN
		{
			get
			{
				return this._MK_DN;
			}
			set
			{
				if ((this._MK_DN != value))
				{
					this.OnMK_DNChanging(value);
					this.SendPropertyChanging();
					this._MK_DN = value;
					this.SendPropertyChanged("MK_DN");
					this.OnMK_DNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_SINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_SINH
		{
			get
			{
				return this._NGAY_SINH;
			}
			set
			{
				if ((this._NGAY_SINH != value))
				{
					this.OnNGAY_SINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_SINH = value;
					this.SendPropertyChanged("NGAY_SINH");
					this.OnNGAY_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NVarChar(200)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOI_TINH", DbType="Bit")]
		public System.Nullable<bool> GIOI_TINH
		{
			get
			{
				return this._GIOI_TINH;
			}
			set
			{
				if ((this._GIOI_TINH != value))
				{
					this.OnGIOI_TINHChanging(value);
					this.SendPropertyChanging();
					this._GIOI_TINH = value;
					this.SendPropertyChanged("GIOI_TINH");
					this.OnGIOI_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DON_DAT_HANG", Storage="_DON_DAT_HANGs", ThisKey="MA_KH", OtherKey="MA_KH")]
		public EntitySet<DON_DAT_HANG> DON_DAT_HANGs
		{
			get
			{
				return this._DON_DAT_HANGs;
			}
			set
			{
				this._DON_DAT_HANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DON_DAT_HANGs(DON_DAT_HANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_DON_DAT_HANGs(DON_DAT_HANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SAN_PHAM")]
	public partial class SAN_PHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_SP;
		
		private string _MA_MAU;
		
		private System.Nullable<int> _MA_LOAI;
		
		private string _TEN_SP;
		
		private System.Nullable<double> _GIA_MUA;
		
		private System.Nullable<double> _GIA_BAN;
		
		private System.Nullable<int> _SL;
		
		private string _MO_TA;
		
		private string _HINH_ANH;
		
		private string _HINH_ANH1;
		
		private EntitySet<CT_DON_HANG> _CT_DON_HANGs;
		
		private EntitySet<HINH_ANH> _HINH_ANHs;
		
		private EntitySet<KICH_THUOC> _KICH_THUOCs;
		
		private EntityRef<LOAI_SP> _LOAI_SP;
		
		private EntityRef<MAU> _MAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_SPChanging(int value);
    partial void OnMA_SPChanged();
    partial void OnMA_MAUChanging(string value);
    partial void OnMA_MAUChanged();
    partial void OnMA_LOAIChanging(System.Nullable<int> value);
    partial void OnMA_LOAIChanged();
    partial void OnTEN_SPChanging(string value);
    partial void OnTEN_SPChanged();
    partial void OnGIA_MUAChanging(System.Nullable<double> value);
    partial void OnGIA_MUAChanged();
    partial void OnGIA_BANChanging(System.Nullable<double> value);
    partial void OnGIA_BANChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    partial void OnMO_TAChanging(string value);
    partial void OnMO_TAChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnHINH_ANH1Changing(string value);
    partial void OnHINH_ANH1Changed();
    #endregion
		
		public SAN_PHAM()
		{
			this._CT_DON_HANGs = new EntitySet<CT_DON_HANG>(new Action<CT_DON_HANG>(this.attach_CT_DON_HANGs), new Action<CT_DON_HANG>(this.detach_CT_DON_HANGs));
			this._HINH_ANHs = new EntitySet<HINH_ANH>(new Action<HINH_ANH>(this.attach_HINH_ANHs), new Action<HINH_ANH>(this.detach_HINH_ANHs));
			this._KICH_THUOCs = new EntitySet<KICH_THUOC>(new Action<KICH_THUOC>(this.attach_KICH_THUOCs), new Action<KICH_THUOC>(this.detach_KICH_THUOCs));
			this._LOAI_SP = default(EntityRef<LOAI_SP>);
			this._MAU = default(EntityRef<MAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_SP
		{
			get
			{
				return this._MA_SP;
			}
			set
			{
				if ((this._MA_SP != value))
				{
					this.OnMA_SPChanging(value);
					this.SendPropertyChanging();
					this._MA_SP = value;
					this.SendPropertyChanged("MA_SP");
					this.OnMA_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MAU", DbType="NVarChar(10)")]
		public string MA_MAU
		{
			get
			{
				return this._MA_MAU;
			}
			set
			{
				if ((this._MA_MAU != value))
				{
					if (this._MAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_MAUChanging(value);
					this.SendPropertyChanging();
					this._MA_MAU = value;
					this.SendPropertyChanged("MA_MAU");
					this.OnMA_MAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI", DbType="Int")]
		public System.Nullable<int> MA_LOAI
		{
			get
			{
				return this._MA_LOAI;
			}
			set
			{
				if ((this._MA_LOAI != value))
				{
					if (this._LOAI_SP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LOAIChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI = value;
					this.SendPropertyChanged("MA_LOAI");
					this.OnMA_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_SP", DbType="NVarChar(50)")]
		public string TEN_SP
		{
			get
			{
				return this._TEN_SP;
			}
			set
			{
				if ((this._TEN_SP != value))
				{
					this.OnTEN_SPChanging(value);
					this.SendPropertyChanging();
					this._TEN_SP = value;
					this.SendPropertyChanged("TEN_SP");
					this.OnTEN_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_MUA", DbType="Float")]
		public System.Nullable<double> GIA_MUA
		{
			get
			{
				return this._GIA_MUA;
			}
			set
			{
				if ((this._GIA_MUA != value))
				{
					this.OnGIA_MUAChanging(value);
					this.SendPropertyChanging();
					this._GIA_MUA = value;
					this.SendPropertyChanged("GIA_MUA");
					this.OnGIA_MUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_BAN", DbType="Float")]
		public System.Nullable<double> GIA_BAN
		{
			get
			{
				return this._GIA_BAN;
			}
			set
			{
				if ((this._GIA_BAN != value))
				{
					this.OnGIA_BANChanging(value);
					this.SendPropertyChanging();
					this._GIA_BAN = value;
					this.SendPropertyChanged("GIA_BAN");
					this.OnGIA_BANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_TA", DbType="NVarChar(MAX)")]
		public string MO_TA
		{
			get
			{
				return this._MO_TA;
			}
			set
			{
				if ((this._MO_TA != value))
				{
					this.OnMO_TAChanging(value);
					this.SendPropertyChanging();
					this._MO_TA = value;
					this.SendPropertyChanged("MO_TA");
					this.OnMO_TAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NVarChar(200)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH1", DbType="NVarChar(200)")]
		public string HINH_ANH1
		{
			get
			{
				return this._HINH_ANH1;
			}
			set
			{
				if ((this._HINH_ANH1 != value))
				{
					this.OnHINH_ANH1Changing(value);
					this.SendPropertyChanging();
					this._HINH_ANH1 = value;
					this.SendPropertyChanged("HINH_ANH1");
					this.OnHINH_ANH1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_CT_DON_HANG", Storage="_CT_DON_HANGs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<CT_DON_HANG> CT_DON_HANGs
		{
			get
			{
				return this._CT_DON_HANGs;
			}
			set
			{
				this._CT_DON_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_HINH_ANH", Storage="_HINH_ANHs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this._HINH_ANHs;
			}
			set
			{
				this._HINH_ANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SAN_PHAM_KICH_THUOC", Storage="_KICH_THUOCs", ThisKey="MA_SP", OtherKey="MA_SP")]
		public EntitySet<KICH_THUOC> KICH_THUOCs
		{
			get
			{
				return this._KICH_THUOCs;
			}
			set
			{
				this._KICH_THUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_SP_SAN_PHAM", Storage="_LOAI_SP", ThisKey="MA_LOAI", OtherKey="MA_LOAI", IsForeignKey=true)]
		public LOAI_SP LOAI_SP
		{
			get
			{
				return this._LOAI_SP.Entity;
			}
			set
			{
				LOAI_SP previousValue = this._LOAI_SP.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_SP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_SP.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._LOAI_SP.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._MA_LOAI = value.MA_LOAI;
					}
					else
					{
						this._MA_LOAI = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAI_SP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAU_SAN_PHAM", Storage="_MAU", ThisKey="MA_MAU", OtherKey="MA_MAU", IsForeignKey=true)]
		public MAU MAU
		{
			get
			{
				return this._MAU.Entity;
			}
			set
			{
				MAU previousValue = this._MAU.Entity;
				if (((previousValue != value) 
							|| (this._MAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAU.Entity = null;
						previousValue.SAN_PHAMs.Remove(this);
					}
					this._MAU.Entity = value;
					if ((value != null))
					{
						value.SAN_PHAMs.Add(this);
						this._MA_MAU = value.MA_MAU;
					}
					else
					{
						this._MA_MAU = default(string);
					}
					this.SendPropertyChanged("MAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_DON_HANGs(CT_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_CT_DON_HANGs(CT_DON_HANG entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
		
		private void attach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
		
		private void attach_KICH_THUOCs(KICH_THUOC entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = this;
		}
		
		private void detach_KICH_THUOCs(KICH_THUOC entity)
		{
			this.SendPropertyChanging();
			entity.SAN_PHAM = null;
		}
	}
}
#pragma warning restore 1591
